//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_10_2_18
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public long Id { get; set; }
        public string HostName { get; set; }
        public string IP { get; set; }
        public string Mac { get; set; }
    }
}
